name: Deploy Busspass mobile api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: amr
    steps:
      - name: stop the server if running
        run: |
          sudo systemctl stop bus-pass-mobile-api
          sudo systemctl stop bus-pass-college-api
          sudo systemctl stop bus-pass-service-api
          sudo systemctl stop bus-pass-admin-api

      - name: Update the repo
        working-directory: /home/github/bus-pass-server/
        run: |
         git pull

      - name: Setup enviornment variables
        working-directory: /home/github/bus-pass-server/
        run: |
          echo "POSTGRESQL_USERNAME=\"${{ secrets.POSTGRESQL_USERNAME }}\"" > .env
          echo "POSTGRESQL_HOST=\"${{ secrets.POSTGRESQL_HOST }}\"" >> .env
          echo "POSTGRESQL_DATABASE=\"${{ secrets.POSTGRESQL_DATABASE }}\"" >> .env
          echo "POSTGRESQL_PASSWORD=\"${{ secrets.POSTGRESQL_PASSWORD }}\"" >> .env
          echo "POSTGRESQL_PORT=\"${{ secrets.POSTGRESQL_PORT }}\"" >> .env
          echo "JWT_SECRET_KEY=\"${{ secrets.JWT_SECRET_KEY }}\"" >> .env
          echo "ENDPOINT_URL=\"${{ secrets.ENDPOINT_URL }}\"" >> .env
          echo "BUSPASS_SERVER_MOBILE_API_PORT=\"${{ secrets.BUSPASS_SERVER_MOBILE_API_PORT }}\"" >> .env
          echo "TELEGRAM_BOT_TOKEN=\"${{ secrets.TELEGRAM_BOT_TOKEN }}\"" >> .env
          echo "TELEGRAM_CHAT_ID=\"${{ secrets.TELEGRAM_CHAT_ID }}\"" >> .env

      - name: copy enviornment variables
        working-directory: /home/github/bus-pass-server/
        run: |
          cp .env mobile-app
          cp .env college-web
          cp .env super-admin-web
          cp .env bus-service-web

      - name: Install packages for mobile app api
        working-directory: /home/github/bus-pass-server/mobile-app/
        run: npm i
      - name: Install packages for bus service api
        working-directory: /home/github/bus-pass-server/bus-service-web/
        run: npm i
      - name: Install packages for college web api
        working-directory: /home/github/bus-pass-server/college-web/
        run: npm i
      - name: Install packages for super admin api
        working-directory: /home/github/bus-pass-server/super-admin-web/
        run: npm i

      - name: Start the server
        run: |
          sudo systemctl restart bus-pass-mobile-api
          sudo systemctl restart bus-pass-college-api
          sudo systemctl restart bus-pass-service-api
          sudo systemctl restart bus-pass-admin-api
    
      - name: send telegram message on push
        working-directory: /home/github/
        run: |
          export MESSAGE=" ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}"
          ./notify.sh "$MESSAGE"

