name: Deploy Busspass mobile api

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: amr
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to destination
        run: rsync -av --delete $GITHUB_WORKSPACE/ /home/github/bus-pass-api/
      - name: idk
        working-directory: /home/github/bus-pass-api/
        run: touch xd
