name: Deploy Busspass mobile api

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: amr
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to destination
        run: rsync -av --delete $GITHUB_WORKSPACE/ /home/github/bus-pass-api/
      - name: Install packages
        working-directory: /home/github/bus-pass-api/mobile-app/
        run: |
          if sudo systemctl is-active --quiet bus-pass-api; then
            echo "Service is running"
            sudo systemctl restart bus-pass-api
          else
            echo "Service is not running"
            sudo systemctl start bus-pass-api
          fi
