name: Deploy Busspass mobile api

on:
  workflow_dispatch:

jobs:
  testingg:
    runs-on: amr
    steps:
      - name: print working dir
        working-directory: $GITHUB_WORKSPACE/
        run: pwd > here
