name: Deploy Busspass mobile api

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: amr
    steps:
      - name: stop the server if running
        working-directory: /home/github/bus-pass-server/mobile-app/
        run: sudo systemctl stop bus-pass-api
        
      - name: Update the repo
        working-directory: /home/github/bus-pass-server/
        run: |
         git pull

      - name: Setup enviornment variables
        working-directory: /home/github/bus-pass-server/mobile-app/
        run: |
          echo "SSRP_BOT_TOKEN=\"${{ secrets.POSTGRESQL_USERNAME }}\"" > .env
          echo "SSRP_DB_HOST=\"${{ secrets.POSTGRESQL_HOST }}\"" >> .env
          echo "SSRP_DB_PW=\"${{ secrets.POSTGRESQL_DATABASE }}\"" >> .env
          echo "SSRP_DB_PORT=\"${{ secrets.POSTGRESQL_PASSWORD }}\"" >> .env
          echo "SSRP_DB_USERNAME=\"${{ secrets.POSTGRESQL_PORT }}\"" >> .env
          echo "SSRP_FACTIONBOT_DB=\"${{ secrets.JWT_SECRET_KEY }}\"" >> .env
          echo "SSRP_FACTIONBOT_DB=\"${{ secrets.ENDPOINT_URL }}\"" >> .env
          echo "SSRP_FACTIONBOT_DB=\"${{ secrets.BUSPASS_SERVER_MOBILE_API_PORT }}\"" >> .env

      - name: Install packages
        run: npm i

      - name: Start the server
        run: sudo systemctl restart bus-pass-api
