name: Deploy Busspass mobile api

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: amr
    steps:
      - name: stop the server if running
        working-directory: /home/github/bus-pass-server/mobile-app/
        run: sudo systemctl stop bus-pass-api

      - name: Update the repo
        working-directory: /home/github/bus-pass-server/
        run: |
         git pull

      - name: Setup enviornment variables
        working-directory: /home/github/bus-pass-server/mobile-app/
        run: |
          echo "POSTGRESQL_USERNAME=\"${{ secrets.POSTGRESQL_USERNAME }}\"" > .env
          echo "POSTGRESQL_HOST=\"${{ secrets.POSTGRESQL_HOST }}\"" >> .env
          echo "POSTGRESQL_DATABASE=\"${{ secrets.POSTGRESQL_DATABASE }}\"" >> .env
          echo "POSTGRESQL_PASSWORD=\"${{ secrets.POSTGRESQL_PASSWORD }}\"" >> .env
          echo "POSTGRESQL_PORT=\"${{ secrets.POSTGRESQL_PORT }}\"" >> .env
          echo "JWT_SECRET_KEY=\"${{ secrets.JWT_SECRET_KEY }}\"" >> .env
          echo "ENDPOINT_URL=\"${{ secrets.ENDPOINT_URL }}\"" >> .env
          echo "BUSPASS_SERVER_MOBILE_API_PORT=\"${{ secrets.BUSPASS_SERVER_MOBILE_API_PORT }}\"" >> .env

      - name: Install packages
        working-directory: /home/github/bus-pass-server/mobile-app/
        run: npm i

      - name: Start the server
        run: sudo systemctl restart bus-pass-api
    
      - name: send telegram message on push
        working-directory: /home/github/
        run: |
          export MESSAGE=" ${{ github.actor }} created commit:
          Commit message: ${{ github.event.commits[0].message }}
          Repository: ${{ github.repository }}
          See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}"
          ./notify.sh "$MESSAGE"

